### ISSUE TITLE
建议可以自定义模板文件目录

### ISSUE THREAD

**Issue by wfsdaj** [cleey/phppoem#95]
现在模板文件分散在每个模块下，不便于制作主题。
建议参考其他框架，统一放在根目录的 views 目录下。😁

**Comment by devtoolman** [comment]
配置文件(app/config.php) 指定 "view_path" 既模板目录即可

**Comment by cleey** [comment]
配置文件(app/config.php) 指定 "view_path" 既模板目录即可
